[package]
name = "notes_server"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0"
uuid = { version = "1.0", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base62 = "2.0"
actix-files = "0.6"
